import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-grey-100">
        <div className="animate-pulse-gold flex h-screen flex-col items-center text-white">
          {children}
        </div>
      </body>
    </html>
  );
}
